# name: Docker Build and Push
# on: push
# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and Push Frontend
#         run: |
#          #refer the docker compose file and dockerfiles from the repository

#       - name: Build and Push Backend
#         run: |
#          #refer the docker compose file and dockerfiles from the repository

#       # Optional: DB image if not using Render's managed DB
#       - name: Build and Push DB
#         run: |
#          #refer the docker compose file and dockerfiles from the repository




name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bmi-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bmi-backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bmi-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bmi-frontend:latest

      # Optional: only include if you are building a custom DB image
      - name: Build and Push DB
        if: exists('db/Dockerfile')
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bmi-db:latest ./db
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bmi-db:latest
